### ISSUE TITLE
Certificates / keys need passphrase?

### ISSUE THREAD

**Issue by tnordstrom** [OpenLEADR/openleadr-python#102]
There is a list of certificates, keys, etc here: https://github.com/OpenLEADR/openleadr-python/tree/main/certificates
But what is the passphrase for each of the keys?
Pardon me if this has been documented elsewhere, I took a look but couldn't find anything.

**Comment by stan-janssen** [comment]
The password for the dummy certificates is `openadr`. I realise now that I didn't document it anywhere except for the test suite where I use these certs: https://github.com/OpenLEADR/openleadr-python/blob/main/test/test_signatures.py#L30

**Comment by tnordstrom** [comment]
Thank you for that info.
