### ISSUE TITLE
VEN report configuration is not developer friendly

### ISSUE THREAD

**Issue by francisrsandoval** [OpenLEADR/openleadr-python#109]
A VEN sets the data_collection_mode of a report, but this value is not exposed to the VTN. Unfortunately, the return values of the VTN report handler depend on the value of data_collection_mode. The design is not clear as it appears that the VTN must have a priori knowledge of VEN behavior (perhaps this is intended to be agreed upon in a ‘program definition’

**Comment by stan-janssen** [comment]
The VTN should not care about the `data_collection_mode` of the VEN's side. Let's assume the following scenario:


- Sampling Interval = 1 minute
- Report Interval = 15 minutes

If `data_collection_mode` = `'incremental'`, the OpenADR Client will call the data collection function once a minute, gather up 15 minute's worth of samples, and then send the report. The VTN simply receives a report with 15 minutes' worth of values.

If `data_collection_mode` = `full`, the OpenADR client will call the data collection function **once** every 15 minutes, and that data collection function should return 15 minutes worth of data. The VTN, again, simply receives a report with 15 minutes' worth of values.

This means that there should be no difference between the two client configurations as far as the VTN is concerned. What is the difference that you are seeing?

Can you describe the scenario that you are using?

**Comment by stan-janssen** [comment]
I'm closing this issue. If it is still relevant, please comment on it. Thanks!
