### ISSUE TITLE
DEBUG logging does not emit XML payloads from VTN

### ISSUE THREAD

**Issue by francisrsandoval** [OpenLEADR/openleadr-python#110]
Where DEBUG level appears to configure VEN to print 2 instances of an XML payload, the VTN prints python dict representations of payloads. It would be very helpful to see the XML on both sides of the exchange to aid testing.

**Comment by stan-janssen** [comment]
You're right; the logging of XML messages was inconsistent across the application. I've made some changes so that each side will debug-log every message that gets parsed and every message that gets created. Hopefully this is more useful.
