### ISSUE TITLE
OpenLEADR as a Gateway

### ISSUE THREAD

**Issue by IainEpps** [OpenLEADR/openleadr-python#127]
Hi Stan (and others),
Firstly, thank you for all your efforts and those of your collaborators with OpenLEADR.  I'm new to both OpenADR and Python (and GitHub) so the learning curve is step but the resources you've put together are proving to be very helpful. 

I have a question regarding the usage of the OpenLEADR VEN client purely as a "gateway" to downstream devices.   From my reading of the documentation it appears possible for a single OpenLEADR VEN client to provide reports to a VTN from downstream devices based on "resource_id" and to respond to events from a VTN directed to those same downstream resources using "resource_id" in the events "Target".  

Is my understand of the OpenLEADR VEN client functionality correct and can it act as a gateway in this way and essentially directly "pass-through" reports and events from the VTN directly to the downstream devices?  

Thanks in advance for your response.
Best regards, Iain

**Comment by stan-janssen** [comment]
Hi Ian,

Depends on what you mean by 'pass-through'. OpenLEADR is not intended to literally pass-through the OpenADR XML messages to other things; it is intended to handle communication to a VTN, and then send commands using some internal logic to the relevant devices. If that is what you want, then: yes, this is what OpenLEADR can do for you.

If you are trying to 'bundle' devices that already speak OpenADR themselves and use OpenLEADR as a simple pass-through service, that's not really easy to do at the moment I think.

Let me know if this helps. If you can tell me a bit about your use case, I might be able to help.

Thanks

**Comment by IainEpps** [comment]
Thanks for the response Stan,

Our use-case is the former you describe whereby the OpenLEADR instance would handle all the OpenADR comms with the VTN as well as the non-OpenADR commands to the downstream devices.  

However, I want a single instance of the OpenLEADR to handle the comms to multiple downstream devices but for it not have to fulfil the other requirements if it was to be a "VTN" rather than just a "Gateway".

The existing fleet of downstream devices can't implement OpenADR comms so I was wondering if a single instance of an OpenLEADR VEN could handle all the VTN comms on behalf of the downstream devices.  Therefore, to the VTN, each of the downstream devices would each look like a single OpenADR "VEN" albeit the VTN would be addressing them via the resource_id.

I want to avoid the "Gateway" having to fulfil the full requirements of being a "VTN" as there's no plan for it to do any "aggregation" or other business logic on behalf of the downstream devices.  The "Gateway" is purely acting as an OpenADR "interpreter" for the comms between the VTN and the downstream devices. 

Thanks again for you thoughts

Best Regards, Iain

**Comment by stan-janssen** [comment]
This is very much something that you can use OpenLEADR for. You can have a VEN running as your gateway and implement the handling of Events and report values the way you want, to as many devices as you want. If you have any specific questions that you'd like help with, let me know.
