### ISSUE TITLE
r_id randomly generated when specified by the client

### ISSUE THREAD

**Issue by manelsb4-irec** [OpenLEADR/openleadr-python#130]
Hello,

According with documentation:

> `report_specifier_id` (str) – A unique identifier for this report. Leave this blank for a random generated id, or fill it in if your VTN depends on this being a known value, or if it needs to be constant between restarts of the client.

>` r_id` (str) – A unique identifier for a datapoint in a report. The same remarks apply as for the report_specifier_id.

But when a `r_id` is introduced as an argument in `add_report` method, `r_id` is still randomly generated.

Am I missing something or is it correct?

Thank you in advance.

Manel

**Comment by stan-janssen** [comment]
You are correct that `r_id` was not correctly used. Should be fixed in the next release!
