### ISSUE TITLE
Clients should send oadrRegisterReport even when no reports are registered

### ISSUE THREAD

**Issue by juantxorena** [OpenLEADR/openleadr-python#132]
Hello,

I think I've found a bug in the clients. According to the OpenADR 2.0b specs, a VEN (and a VTN, but I haven't tested it yet, I'm implementing a VEN) should sent a METADATA report even when it doesn't support any reporting capabilities, for informing the VTN that it doesn't have any.

Maybe I'm doing it wrong, but it doesn't seem to send anything if no reports are registered.

Any comments?

**Comment by stan-janssen** [comment]
You may be right; I think this needs to be added to the client code.
