### ISSUE TITLE
Expected the OadrRegisterReport.ReportRequestID to be empty

### ISSUE THREAD

**Issue by juantxorena** [OpenLEADR/openleadr-python#134]
When testing for the certifications, I get this error when registering reports:
Expected the OadrRegisterReport.ReportRequestID to be empty

The ReportRequestID has to be 0 for the oadr:oadrReport elements, but not for the oadr:oadrRegisterReport

**Comment by stan-janssen** [comment]
Thanks for the report, I'll have a look.
