### ISSUE TITLE
Client has to answer with a oadrRegisteredReport even if it doesn't has to send any report

### ISSUE THREAD

**Issue by juantxorena** [OpenLEADR/openleadr-python#135]
As per specs, actually in DR Programming guide:

_Note that both VENs and VTNs are capable of being both a report producer and a report
requestor, so all the payloads below can be initiated by either party.

oadrRegisteredReport -Acknowledge the receipt of oadrRegisterReport, optionally
request one of the offered reports_

The current implementation doesn't do anything if there's no reports to register, so the conformation tests fail.

**Comment by juantxorena** [comment]
Even when the received oadrRegisterReport has reports, it tries to call an non-existing self.register_report method. Assuming it's a bug and it should be "on_register_report", that doesn't work neither because it cannot be added as a handler, since "'handler' must be either on_event or on_update_event"

**Comment by stan-janssen** [comment]
>  it tries to call an non-existing self.register_report method

This method does exist in client.py: [see here](https://github.com/OpenLEADR/openleadr-python/blob/0b8bf61249d8393678f261c339e5558994bc7667/openleadr/client.py#L480).

Are you talking about the VTN code?

**Comment by stan-janssen** [comment]
Are you talking about the case where the VTN is offering reports to the VEN? That is a use case that is not (yet) supported in OpenLEADR. I've understood that it is a very uncommon use case.

**Comment by juantxorena** [comment]
Yes, I'm talking about that case. It may be uncommon, but it's needed for compilance. In any case, the poll expects oadrRegisterReport messages ([here](https://github.com/OpenLEADR/openleadr-python/blob/0b8bf61249d8393678f261c339e5558994bc7667/openleadr/client.py#L920)), so IMHO it should return something even if is not yet supported. I assumed it was a typo and it was supposed to call on_register_report, so I changed the code to make it work for the tests. I can do a pull request with this changes, but it's not very clean, and I'm far for being a python expert.

**Comment by stan-janssen** [comment]
All right, I'll make sure that the oadrRegisterReport request is handled properly for now, and implement receiving reports from the VTN at a later time (as well as sending reports from the VTN, which is not supported right now either). Thanks!
