### ISSUE TITLE
Issue with Event Cancellation: cancel_event does not remove the event

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#169]
Hi OpenLEADR team,

I have been integrating OpenLEADR into a project and encountered an issue with the cancellation of events. Currently, I am using the `cancel_event` method in `server.py` to mark events as "cancelled," but I observe that these events are still present in the list of events when queried.

Here is the code for my `handle_cancel_event` method in the backend:

```
async def handle_cancel_event(request):
    payload = await request.json()
    ven_id = payload.get("ven_id")
    event_id = payload.get("event_id")

    if not ven_id or not event_id:
        raise web.HTTPBadRequest(text="Missing ven_id or event_id")

    request.app["server"].cancel_event(ven_id, event_id)
    print(f"Cancelled event {event_id} for VEN {ven_id}")
    return web.json_response({"status": "success", "message": f"Event {event_id} cancelled for VEN {ven_id}"})

```

Here is the setup for my OpenADRServer instance and routes:
```
# Create the OpenADRServer instance
server = OpenADRServer(
    vtn_id="bens_vtn",
)

# Add the handlers for VEN registrations and reports
server.add_handler("on_create_party_registration", on_create_party_registration)
server.add_handler("on_register_report", on_register_report)

# Set up CORS and routes for handling VEN and event operations
cors = aiohttp_cors.setup(
    server.app,
    defaults={
        "*": aiohttp_cors.ResourceOptions(
            allow_credentials=True,
            expose_headers="*",
            allow_headers="*",
        )
    },
)

# Add routes to the server
resource = cors.add(server.app.router.add_resource("/api/ven"))
cors.add(resource.add_route("POST", handle_ven_post))

resource = cors.add(server.app.router.add_resource("/api/event"))
cors.add(resource.add_route("POST", handle_event_post))

resource = cors.add(server.app.router.add_resource("/api/all_events"))
cors.add(resource.add_route("GET", handle_list_all_events))

resource = cors.add(server.app.router.add_resource("/api/cancel_event"))
cors.add(resource.add_route("POST", handle_cancel_event))
```

While the method marks the event as "cancelled," it remains in the event list as shown by the `handle_list_all_events` method:
```
async def handle_list_all_events(request):
    events_list = []
    print("Listing all events...")
    try:
        for ven_id, events in request.app["server"].events.items():
            print(f"VEN ID: {ven_id}, Events: {events}")
            for event in events:
                event_id = event.event_descriptor.event_id
                event_name = event.event_signals[0].signal_name
                event_type = event.event_signals[0].signal_type
                event_start = event.active_period['dtstart']
                event_duration = event.active_period['duration']
                events_list.append({
                    "ven_id": ven_id,
                    "event_id": event_id,
                    "event_name": event_name,
                    "event_type": event_type,
                    "event_start": event_start.isoformat(),
                    "event_duration": event_duration.total_seconds() / 60
                })
        return web.json_response(events_list)
    except Exception as e:
        print(f"Error listing events: {e}")
        raise web.HTTPInternalServerError(text=str(e))
```
When I call the cancellation API, the logs show that the event is marked as cancelled, but it still appears in the event list as a cancelled event.

**Expected Behavior:**

- I expect the `cancel_event` method to completely remove the event from the list of events. Unless I am missing something with the way Openleadr behaves or handles event?

Thanks for your help and the great work on OpenLEADR!

**Comment by HaolongEdward** [comment]
Hi @bbartling , 

First of all, I am no expert in this topic either. The following may not be right at all.  

But from what I understand so far, you do not want to directly remove the event from the list of events. At least not until all involved VENs have been notified the event is cancelled. Instead, the library marks it as cancelled and increases the `modification_number` by 1. 

So if you go to this file https://github.com/OpenLEADR/openleadr-python/blob/main/openleadr/client.py, line 939, which is how the VEN (client) handles a new/updated event. In this function, you can also find the logic of how the VEN handles an updated/cancelled event. 

I hope this explanation makes your life a bit easier. 

Cheers. 
Edward

**Comment by bbartling** [comment]
Ah that makes perfect sense. I'll experiment with that. Thank you!
