### ISSUE TITLE
In normalize_dict, if a value in a key/value pair is number 0, the parse_int will return a string rather than int

### ISSUE THREAD

**Issue by jmuraca** [OpenLEADR/openleadr-python#24]
Example: <eiop:modificationNumber>0</eiop:modificationNumber>

When evaluating this in util->normalize_dict function

elif isinstance(value, str):
            d[key] = parse_int(value) or parse_float(value) or value

parse_int and parse_float return 0 and 0.00 correctly, as these are "falsey" they are false and the last value is returned, which is the actual previous parsed value string(0)

**Comment by jmuraca** [comment]
No chance to checkout and change now, but will try to commit tomorrow.
Check if string is numeric -> convert to float
Once as a float, check if that number is an int -> convert to int

I'm not blown away by this approach, but it works

```
elif isinstance(value, str):
    if(value.isnumeric()):
        d[key] = parse_float(value)
        if(d[key].is_integer()):
            d[key] = parse_int(value)
    else:
        d[key] = value
```

**Comment by stan-janssen** [comment]
That's a bug indeed! I think it might be best to inline the parse_int and parse_float functions here, since this is the only place where they are used. Something like:

```python
        elif isinstance(value, str):
            if re.match(r'^-?\d+$', value):
                d[key] = int(value)
            elif re.match(r'^-?[\d.]+$', value):
                d[key] = float(value)
```

Thanks for reporting this. I'll add this fix in a next update.
