### ISSUE TITLE
Documentation outdated on VEN registration explanation

### ISSUE THREAD

**Issue by cirochang** [OpenLEADR/openleadr-python#25]
I believe the example implementation described here: 
https://github.com/OpenLEADR/openleadr-python/blob/main/docs/server.rst 
is outdated.

This example implementation:
```
from openleadr.utils import generate_id

async def on_create_party_registration(payload):
    ven_id = payload['ven_id']
    # Check whether or not this VEN is allowed to register
    result = await database.query("""SELECT COUNT(*)
                                       FROM vens
                                      WHERE ven_id = ?""",
                                  (payload['ven_id'],))
    if result == 1:
        # Generate an ID for this registration
        registration_id = generate_id()

        # Store the registration in a database (pseudo-code)
        await database.query("""UPDATE vens
                                   SET registration_id = ?
                                 WHERE ven_id = ?""",
                             (registration_id, ven_id))

        # Return the registration ID.
        # This will be put into the correct form by the OpenADRServer.
        return registration_id
```

wont work, since the response should be a tuple (ven_id, registration_id).
Also `payload['ven_id']` doesn't exist anymore.

Please correct me if I am wrong.

**Comment by stan-janssen** [comment]
Thanks for the report, you are absolutely correct. I have been reworking parts of openleadr over the past few weeks, and it seems that the documentation has not kept up everywhere. I'll be fixing the docs soon.

In the meantime, yes, the on_create_party_registration should return a `ven_id, registration_id tuple`. `payload['ven_id']` will exist if the Client passed a ven_id during registration, which by default is probably not the case.

**Comment by cirochang** [comment]
Got it! Thank you @stan-janssen for the fast reply!
