### ISSUE TITLE
Add a raw event with a callback

### ISSUE THREAD

**Issue by cirochang** [OpenLEADR/openleadr-python#35]
I am trying to add an event with two EventSignal (simple and ELECTRICITY_PRICE). But it seems that is not possible to do that using `add_event` method because it adds just one EventSignal per event. So I decided to use `add_raw_event` method, but then I realized that the callback is not being set on `add_raw_event` method.

https://github.com/OpenLEADR/openleadr-python/blob/2f68966b16b4b85efd16922787294802dac384f6/openleadr/server.py#L229-L238

**Comment by stan-janssen** [comment]
Thank for reporting this. I just added support for the callback in version 0.5.14. Please try that version and let me know if it works for you.

**Comment by cirochang** [comment]
Thank you @stan-janssen ! It worked well!
