### ISSUE TITLE
Typo on SIGNAL_TYPE

### ISSUE THREAD

**Issue by MaiteEtxandi** [OpenLEADR/openleadr-python#41]
Small typo on openleadr.enums class SIGNAL_TYPE

X_LOAD_CONTROL_PERCENT_OFFSET = "x-loadControlPorcentOffset"
should be
X_LOAD_CONTROL_PERCENT_OFFSET = "x-loadControlP**e**rcentOffset"

**Comment by stan-janssen** [comment]
Thanks! I fixed in in `main`, will be included in the next release.

**Comment by stan-janssen** [comment]
This is now released as part of version 0.5.17.
