### ISSUE TITLE
1-minute VTN example error

### ISSUE THREAD

**Issue by GeorgeIoak** [OpenLEADR/openleadr-python#50]
The [example code](https://openleadr.org/docs/server.html) in the docs is incorrect for the add_event:

```
# Add a prepared event for a VEN that will be picked up when it polls for new messages.
server.add_event(ven_id='ven_id_123',
#                 event_name='simple',
#                 event_type='level',
                 signal_name='simple',
                 signal_type='level',
                 intervals=[{'dtstart': datetime(2021, 1, 1, 12, 0, 0, tzinfo=timezone.utc),
                             'duration': timedelta(minutes=10),
                             'signal_payload': 1}])
```
`event_name` and `event_type` need to be changed to `signal_name` and `signal_type`

**Comment by stan-janssen** [comment]
Thanks, should be fixed now!

**Comment by GeorgeIoak** [comment]
I found that you also need to add:
`from functools import partial`

Then when you run the VTN and VEN the output is:
```
george@George-Office3:~$ python3 testVTN.py &
[1] 2997
george@George-Office3:~$ You did not provide a 'callback', which means you won't know if the VEN will opt in or opt out of your event. You should consider adding a callback for this.

********************************************************************************
                       Your VTN Server is now running at
                   http://127.0.0.1:8080/OpenADR2/Simple/2.0b
********************************************************************************


george@George-Office3:~$ python3 testVEN.py
Your on_event handler encountered an error. Will Opt Out of the event. The error was KeyError: 'f800a992-a711-4208-9b85-badd51ce1715'
Ven ven_id_123 reported Voltage = 1.23 at time 2021-01-19 14:53:30.002399+00:00 for resource device001
Ven ven_id_123 reported Voltage = 1.23 at time 2021-01-19 14:53:40.002077+00:00 for resource device001
```

Is the KeyError to be expected?

**Comment by stan-janssen** [comment]
No, the KeyError is not expected. As the warning says:

```
You did not provide a 'callback', which means you won't know if the VEN will opt in or opt out of your event. You should consider adding a callback for this.
```

From the example code:

```python3
async def event_response_callback(ven_id, event_id, opt_type):
    """
    Callback that receives the response from a VEN to an Event.
    """
    print(f"VEN {ven_id} responded to Event {event_id} with: {opt_type}")

...
server.add_event(ven_id='ven_id_123',
                 signal_name='simple',
                 signal_type='level',
                 intervals=[{'dtstart': datetime(2021, 1, 1, 12, 0, 0, tzinfo=timezone.utc),
                             'duration': timedelta(minutes=10),
                             'signal_payload': 1}],
                 callback=event_response_callback)
```

Notice the 'callback' parameter to add_event.

In the current version on the main branch, there will not be an error if you decide not to add a callback to the add_event call. This version (0.5.18) will be released later today.

**Comment by stan-janssen** [comment]
The KeyError looks like it is coming from your `on_event` handler. What does the code for that handler look like?

**Comment by GeorgeIoak** [comment]
I just grabbed the first example from this [page](https://openleadr.org/docs/client.html) which reminds me that I also had to modify the `ven_name` since the VTN example uses `ven123` and the VEN example uses `myven`

I'm just trying to get my feet wet and run some "pre-alpha" tests so I thought those first examples would work. I haven't started digging into the KeyError as I wasn't sure if something else was set up incorrectly yet.

**Comment by stan-janssen** [comment]
I should probably make the examples in the docs compatible with each other from the get-go to help getting up and running.

I also recommend enabling some more automatic logging so you can see what is going on. See the first code snippet on [this page](https://openleadr.org/docs/logging.html) and add them to both your client and server.

If you run into anything else, please let me know. If you have any documentation suggestions, I'm happy to hear those as well. Good luck!

**Comment by GeorgeIoak** [comment]
OK, I'll get back to this a little later today and see what I can uncover. Having a set of example codes that work as a first test would be great. 

My environment right now is Ubuntu 20.0.4 and Python 3.8.5
