### ISSUE TITLE
embed BACnet read request in VEN example

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#51]
Is it possible to embed Python BACnet requests into the VEN example from the documentation? The reason I ask this question is I am worried that I am not complying with Asyncio type code, that my BACnet request could make the entire script synchronous. 

On a test bench using the package [BAC0 ](https://bac0.readthedocs.io/en/latest/)I can print 2 values of temperature sensors from a BACnet device on my test bench LAN with this:

```
import BAC0

bacnet = BAC0.lite()

T1 = bacnet.read('12345:2 analogInput 2 presentValue')
print(T1)

T2 = bacnet.read('12345:2 analogInput 3 presentValue')
print(T2)

bacnet.disconnect()
```

Embedding this into the simple VEN example it works, I can use the temp sensor value as my open ADR report to the virtual top node VTN. (real life I would most likely be using BACnet read for building electrical power, kW)

```
import asyncio
from datetime import timedelta
from openleadr import OpenADRClient, enable_default_logging
import BAC0


#start BACnet server
bacnet = BAC0.lite()
enable_default_logging()

async def collect_report_value():
    #read temp sensor from BACnet device
    T1 = bacnet.read('12345:2 analogInput 2 presentValue')
    print(T1)
    return T1

async def handle_event(event):
    # This callback receives an Event dict.
    # You should include code here that sends control signals to your resources.
    return 'optIn'

# Create the client object
client = OpenADRClient(ven_name='ven123',
                       vtn_url='http://localhost:8080/OpenADR2/Simple/2.0b')

# Add the report capability to the client
client.add_report(callback=collect_report_value,
                  resource_id='device001',
                  measurement='temperature',
                  sampling_rate=timedelta(seconds=60))

# Add event handling capability to the client
client.add_handler('on_event', handle_event)

# Run the client in the Python AsyncIO Event Loop
loop = asyncio.get_event_loop()
loop.create_task(client.run())
loop.run_forever()
```

When I run this code along with the 1-minute VTN example local host on my machine, I can see my BACnet read request on the VTN script command prompt. (shown below)

I am no super expert on what is going on under the hood to make BACnet read requests but I know there is a lot going on I cant see (like a BACnet proxy server running on a certain port number, etc.) and I think I have heard the BACnet code is asynchronous. 

Would there be any tips for best practice to get report data from the building thru BACnet? Would it ever be preferred instead of embedding the BACnet read request code into the VEN script, I should modify to use like a REST API call from the VEN script to a BACnet server to get data? I can make separate BACnet BAC0 script a stand alone rest API with Flask.

Any advice greatly appreciated!

```
Ven ven_id_123 reported temperature = 72.66999816894531 at time 2021-01-30 17:11:00.926180+00:00 for resource device001
Responding to oadrUpdateReport with a oadrUpdatedReport message: {'vtn_id': 'myvtn', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '12836a2b-0588-49c5-84d1-6f632c64f9fe'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '2e61170d-c71e-4bd2-b88f-acec9c52da48'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '0f2e36b0-e46f-40c8-93d0-bfa9df41f712'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': 'a7c49bf1-2938-409f-bde9-6e541221ed29'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': 'f70f21ed-4726-423f-afae-1350bd554ded'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '3d68a49c-2390-40ac-b933-56c14b72773b'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '55d1f5a2-9013-4fdc-bf67-fd5d970bbbec'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '7205b0b2-f711-42a3-9c23-4d48893933c9'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '961ffb93-5cd8-422d-b69f-6269bb581fdf'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '3ba74d1f-ab0c-4e7c-b49a-22321fda310b'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '72e97dc1-f6be-4013-a715-68321698ecda'}.
Ven ven_id_123 reported temperature = 72.5199966430664 at time 2021-01-30 17:12:00.380994+00:00 for resource device001
Responding to oadrUpdateReport with a oadrUpdatedReport message: {'vtn_id': 'myvtn', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': 'ccf90ca7-c23e-4ace-a8eb-c24a45170b93'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': '991991de-0128-4dac-9b42-458682ddbbde'}.
Responding to oadrPoll with a oadrResponse message: {'vtn_id': 'myvtn', 'ven_id': 'ven_id_123', 'response': {'request_id': None, 'response_code': 200, 'response_description': 'OK'}, 'request_id': 'e46df366-f322-49fb-abcf-d6d5319c1a53'}.
```

**Comment by bbartling** [comment]
One small edit here Is I have learned that the BACnet code is _**synchronous**_, so Ill have to find some way to embed synchronous code into asyncio if that is possible... :)

**Comment by stan-janssen** [comment]
Thanks for the question and for the extensive details about your use case. You can absolutely use synchronous callbacks if you want, but during the execution of that function, the entire event loop will be blocked. In practice, if the call happen fast enough, this should be no problem at all. **That would be my first check**: if the retrieval of the data is in the order of less than 200 ms or so, you should probably be fine, unless you want to read many many sensors and your report interval is very short.

(One of the things you might see if you do this, is warnings concerning `TaskWakeupMethWrapper`, which is a cryptic warning that you were blocking the event loop for longer that asyncio would like.)

### Making your blocking code non-blocking

If you're using (or are able to use) Python 3.9, you can use [`asyncio.to_thread`](https://docs.python.org/3/library/asyncio-task.html?#asyncio.to_thread) to wrap a synchronous function. This will run the function in a separate thread which you can await. For example:

```python3
import asyncio

async def collect_report_value():
    #read temp sensor from BACnet device
    T1 = await asyncio.to_thread(bacnet.read('12345:2 analogInput 2 presentValue'))
    print(T1)
    return T1
```

You should only use this if the bacnet.read is thread-safe, because it might be called more than once at a time in the asyncio context.

If you don't use Python 3.9, you can use the slightly more verbose [`loop.run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) like this:

```python3

import asyncio
import concurrent.futures
from functools import partial

async def collect_report_value():
    #read temp sensor from BACnet device
    with concurrent.futures.ThreadPoolExecutor() as pool:
        T1 = await asyncio.run_in_executor(pool, partial(bacnet.read, 
                                                         '12345:2 analogInput 2 presentValue'))
    print(T1)
    return T1
```

If you want to retrieve data from some other system using a REST call, you can use the [aiohttp](https://docs.aiohttp.org/en/stable/client_quickstart.html) library to make these request asyncio and non-blocking. Aiohttp is automatically installed with openleadr, so you should be ready to go for that.

These would allow you to schedule your blocking functions on the event loop without blocking it.

I hope this helps! I'd be happy to discuss this further, to learn about your application.

**Comment by bbartling** [comment]
Hi Stan,

From the author of the Python BACnet stack ([bacpypes](https://bacpypes.readthedocs.io/en/latest/)) its not thread safe at the moment but they are working on a future version that is... The BACnet app that someone created called [BAC0 ](https://bac0.readthedocs.io/en/latest/) (uses bacpypes under the hood) does apparently run on its own thread though. For the time being should I test both?

Would you have any tips for this below `run_in_executor` with a `blocking_io` non asyncio function? This is actually my first time working with asyncio :)

```
import asyncio
from datetime import timedelta
from openleadr import OpenADRClient, enable_default_logging
import BAC0
import concurrent.futures
import numpy
from functools import partial

enable_default_logging()


#apprently runs on its own thread
bacnet = BAC0.lite()


def blocking_io():
    #read temp sensor from BACnet device
    try:
        sensor_value = bacnet.read('12345:2 analogInput 2 presentValue')
        return sensor_value
    except:
        return numpy.nan


async def collect_report_value():
    # 1. Run in the default loop's executor:
    result = await loop.run_in_executor(None, blocking_io)
    return result



async def handle_event(event):
    # This callback receives an Event dict.
    # You should include code here that sends control signals to your resources.
    return 'optIn'

# Create the client object
client = OpenADRClient(ven_name='ven123',
                       vtn_url='http://localhost:8080/OpenADR2/Simple/2.0b')

# Add the report capability to the client
client.add_report(callback=collect_report_value,
                  resource_id='device001',
                  measurement='temperature',
                  sampling_rate=timedelta(seconds=60))

# Add event handling capability to the client
client.add_handler('on_event', handle_event)

# Run the client in the Python AsyncIO Event Loop
loop = asyncio.get_event_loop()
loop.create_task(client.run())
loop.run_forever()
```

Super cool project. I am hoping to test open leadr on a live building this summer for demand response research.

**Comment by jmuraca** [comment]
Could you run the BACnet system as a separate process and write the sensor
values to a local sqlite database or similar? Then the VEN could pull
values from there whenever it needs to.

**Comment by bbartling** [comment]
Sure. I could that easily. OR even use a REST API call to the BACnet system to get the value.

What would be preferred between all this?

1. Shared db like you mentioned
2. REST API from VEN script to local LAN BACnet system
3. Embed BACnet read requests into the VEN script?

Thank you!

**Comment by jmuraca** [comment]
(FYI not a maintainer, just interested in the project!)
Reading this thread and preferring (not requiring?) a 200ms response, a
REST call could easily go over this time. If you could use an intermediate
store like a local SQLite DB to store the telemetry from BACnet, then the
VEN could pick it up as needed, I think that would work well. Would allow
you keep your VEN codebase in sync with this project more easily I'd assume
by having a generic report pulled from the DB, and then the BACnet codebase
could be modified as you add more sensors across different buildings, allow
you to perform logic on the sensor data locally before inserting into the
DB, etc.

**Comment by bbartling** [comment]
Great thanks Ill work on this
