### ISSUE TITLE
Support for pre-allocated VEN ID

### ISSUE THREAD

**Issue by jmuraca** [OpenLEADR/openleadr-python#53]
As a VTN we pre-allocate VEN ID's and communicate these to a customer for installation as it allows us to ensure only valid and secure connections to our VTN, as well as matching VEN's confidently to other entities. 

Pre-allocated VEN ID's are supported within OADR 2.0b Rule 402, and an test harness compliance check under test "VEN Registration - Pre-allocated VEN ID" N1_0025 and N0_5025

Using ven_name is not a perfect analog as this may be used for different commentary like a user readable name or client specific convention.

**Comment by jmuraca** [comment]
Changes required appear to be 
- OpenADRClient.init -> add ven_id as an input parameter
- In OpenADRClient.run, when calling create_party_registration, include self.ven_id as parameter

When creating party registration , ven_id already being check to be added to payload

If this is all, happy to make a pull request for this now

**Comment by jmuraca** [comment]
If I understand the question, the flow to check is
- *something* pre-allocates a VEN ID
- the VEN is started with that VEN ID and querys the VTN sending that VEN ID in the payload
- the VEN ID is not valid at the VTN
- *what happens here*. Assumption is an error is raised indicating VEN is not valid

I don't have a chance to dig into this today

**Comment by jmuraca** [comment]
Per OADR 2.0b Rule 403, When responding to an oadrCreatePartyRegistration.... 

> oadrCreatedPartyRegistration MUST include the following payload elements, unless the oadrCreatedPartyRegistration is sent as a response to an oadrQueryRegistration (in which case inclusion of the elements is optional):
> • registrationID
> • venID

Per OADR 2.0b Rule 404, When responding to an oadrQueryRegistration.... 

> oadrCreatedPartyRegistration MUST NOT include the following payload elements:
> • registrationID – If the VEN has not registered with the VTN yet
> • venID – If the VEN has not registered with the VTN yet 

So within the context of the Client.run function, if not ven_id exists, this would be a OADR non-conformance error. If anything, this error should be thrown within the create_party_registration function when checking for ven_id within the response payload.

I think this is a minor change, if at all, and separate to my pull request to accept and ven_id as input which would be valid in this case.

**Comment by stan-janssen** [comment]
All right, we'll figure out a way to deal with rejected registrations separately. Thanks for the contribution! I will merge the pull request into `main` and it will be released in the next version of OpenLEADR.

**Comment by stan-janssen** [comment]
Your commit was released in version 0.5.20. Thanks again!
