### ISSUE TITLE
Exception in created_event when using an on_poll handler

### ISSUE THREAD

**Issue by ebencollins** [OpenLEADR/openleadr-python#58]
When `polling_method` is `external`, the `created_event` method inside `EventService` causes  the following exception:
```
[2021-03-19 23:17:13,765] - ERROR - openleadr - vtn_service.handler:98 -  An exception occurred during the execution of your EventService handler: UnboundLocalError: local variable 'event_id' referenced before assignment
[2021-03-19 23:17:13,766] - ERROR - openleadr - vtn_service.handler:148 -  The VTN server encountered an error: UnboundLocalError: local variable 'event_id' referenced before assignment
```
This originates from the following code:
https://github.com/OpenLEADR/openleadr-python/blob/ab8b004a03f5c2eef44fed77449c058ec35a1b81/openleadr/service/event_service.py#L113-L114

`event_id` and `opt_type` are only defined in `created_event` when `polling_method` is `internal`. It appears that the issue may have been introduced in cdaa5015e1501b87cc9cc22d55fa63e8c30824d3 when switching the `on_created_event` callback arguments from `payload` to `ven_id, event_id, opt_type`.

**Comment by stan-janssen** [comment]
Thanks for the report. Yes, that's definitely a bug! I'll correct it in the next release, hopefully early next week.

**Comment by stan-janssen** [comment]
A new release is now available, version 0.5.23. I hope you can try that release and let me know if it solves your problem.

Another question: what is the reason that you are using the external polling method? Is there some feature that is not available when using the build-in polling method that I could add?

**Comment by ebencollins** [comment]
It seems to be working as expected now, thanks for the quick patch!

My use case is to enable the VTN to distribute events from a database when they get created manually by a web application. Implementing `on_poll` seemed to be the easiest way to do this while preserving VEN responses between server restarts. My `on_poll` implementation gets events from the database where the VEN hasn't responded to the latest modification and returns `oadrDistributeEvent, {'events': [...]}` if there are events.

I did see `on_request_event` which seemed like it might potentially be the better method to implement, but based on the code and commits it seems to still be a placeholder? When using internal polling, `request_event` is called, but `on_request_event` is not, but when using external polling, `on_poll` is called (negating the need for `on_request_event`.
https://github.com/OpenLEADR/openleadr-python/blob/ab8b004a03f5c2eef44fed77449c058ec35a1b81/openleadr/service/poll_service.py#L119-L123
https://github.com/OpenLEADR/openleadr-python/blob/ab8b004a03f5c2eef44fed77449c058ec35a1b81/openleadr/service/event_service.py#L41-L52

**Comment by stan-janssen** [comment]
You should be able to register the on_request_event handler like this:

```python3

async def on_request_event(ven_id):
    ...
    return [Event(...), Event(...)]

server = OpenADRServer(...)
server.add_handler('on_request_event', on_request_event)
````

This will override the existing placeholder handler. That handler is only there to provide you with a suggestion of how to implement it.
