### ISSUE TITLE
Need some clarification on SSL/TLS

### ISSUE THREAD

**Issue by porkytin** [OpenLEADR/openleadr-python#59]
Hi, I'm starting a project and thinking about using this package, so first of all thanks for your work.

I'm a bit confused with the security part of things. The documentation says in the "Message Signing" section that  "It **does not provide message encryption**; for that, a transport-level encryption (TLS) should be used." 

But looking through the code I've noticed that the VEN is using `aiohttp.TCPConnector(ssl=ssl_context)` and the VTN is using `aiohttp.web.TCPSite` with some `ssl_context`, so I'd think that the connection is being secured. Can you give some guidance about what else would be needed to keep the messages encrypted with TLS?

**Comment by stan-janssen** [comment]
Thanks for the question! 

OpenLEADR will use a secure TLS connection in combination with signed messags. It's just that the message signing part is not responsible for encrypting the message, only for ensuring authenticity. That part of the documentation was only about message signatures, and was simply trying to make that distinction clear.

I will add to that part of the docs that TLS is also provided.

**Comment by porkytin** [comment]
Ok, cool. Thanks for the quick answering :)
