### ISSUE TITLE
Cannot create an instance of the class Event with the event_descriptor with event_status = cancelled

### ISSUE THREAD

**Issue by michal-kowalczyk** [OpenLEADR/openleadr-python#60]
I construct an instance of the EventDescriptor with event_status="cancelled":
https://github.com/OpenLEADR/openleadr-python/blob/main/openleadr/objects.py#L98

Then, I construct an instance of the Event with use of the event_descriptor. Unfortunately, the __post_init__ methods clears out previously set event_status:
https://github.com/OpenLEADR/openleadr-python/blob/main/openleadr/objects.py#L98

While it is possible to cancel that event from the server instance with use of:
https://github.com/OpenLEADR/openleadr-python/blob/main/openleadr/server.py#L294

I think that the event_status should be determined automatically only under some condition, e.g. if it is not set, or at least it is not set to "cancelled".

If the current behavior is expected, I think it should be document.

**Comment by stan-janssen** [comment]
The current behavior is that the event status is automatically determined based on the time and the event schedule. Creating a new event with the status "Cancelled" is an edge case that I don't really want to support right now. What would be the use for this, apart from a testing thing?
