### ISSUE TITLE
Is it possible to implicitely cancel an event (implied cancel)?

### ISSUE THREAD

**Issue by michal-kowalczyk** [OpenLEADR/openleadr-python#61]
In the conformance rule the term "implied cancel" is mentioned. It happens when the VTN sends oadrDistributedEvent message without a previously known event.

While I found no requirement for VTN to support that scenario, I wonder if it is even possible with the current API, so the ven side can be tested?

The only way that I found to simulate that is by cleaning events/events_updated before adding events to the server:

```python
    server.services['event_service'].events = {}
    server.services['poll_service'].events_updated = {}

    server.add_raw_event(ven_id, event, event_callback)
```

**Comment by stan-janssen** [comment]
Implicit cancel is not supported at the moment with the internal event queueing mechanism. You can either use the external mechnasm (ie implement your own on_poll and on_request_event handlers), or use the method you describe above. I'll keep it on my list of possible additions to the API, but I see it mostly as a confusing way of cancelling an event.
