### ISSUE TITLE
OpenLEADR assumes that the X509Certificate ends with new line

### ISSUE THREAD

**Issue by michal-kowalczyk** [OpenLEADR/openleadr-python#63]
When a signed XML message is sent with X509Certificate that is not ended with new line character, OpenLEADR fails to extract the certificate in PEM format. I wasn't able to found a specification which says that OpenLEADR assumption is correct. I believe it should work in both cases.

The code under consideration:
https://github.com/OpenLEADR/openleadr-python/blob/main/openleadr/utils.py#L401

**Comment by stan-janssen** [comment]
The line you cite takes the text from the <X509Certificate> element and prepends and appends the `-----BEGIN CERTIFICATE-----\n` and `-----END CERTIFICATE-----\n` to it. 

Is the problem that without a newline at the end of the cert itself, it becomes invalid?

**Comment by michal-kowalczyk** [comment]
Yes, that's the problem. Here's the log from the VTN:
```
The VTN server encountered an error: Error: [('PEM routines', 'get_header_and_data', 'bad end line')]
```

**Comment by michal-kowalczyk** [comment]
The fix solves the issue. Thanks!
