### ISSUE TITLE
Switch off XML Signature from VEN’s XML messages to VTN

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#69]
Would there be a feature of the openLEADR VEN to be able to switch off the VEN’s XML messages for integrating to a VTN which doesn't support it?

Copy/Paste from the open ADR specs below, is the XML payload is optional? Does the open LEADR VEN have a flag to switch ON or OFF?

> **10.6.2 Components of XML Signatures** 
> Reference URI: This element provides a reference to the resource that is being signed using a 
> URI. 
> Digest Value: This element contains the digest of the resource that is being signed. 
> Signature Value: This element contains the resource digest signed by the private key of the signing authority. 
> Key Info: The key info element contains the information of the key that should be used for signature verification. This contains information on the public key of the signing authority.

**Comment by stan-janssen** [comment]
If you don't want signatures, then don't add the certificate and key to your client. What VTN are you using that does not support signatures?

**Comment by bbartling** [comment]
[IP Keys](https://www.ipkeys.com/) has a free VTN that people can test with. The developer stated that this VTN was developed before open ADR profile B where I think he was stating that they just modified the code enough to accommodate both A and B standards but it may not be completely at the standard. I am going to close this as I dont think I will be testing on this anymore anyway, thanks for the response.
