### ISSUE TITLE
VEN client example reporting a "full" "data_collection_mode" 

### ISSUE THREAD

**Issue by 00javad00** [OpenLEADR/openleadr-python#73]
Hello Stan,
I was wondering if you could help and share a basic VEN example capable of making a `full` report (via `data_collection_mode`) while the `sampling_interval` changes time by time. 
I tried the provided example [here ](https://github.com/OpenLEADR/openleadr-python/blob/main/docs/reporting.rst)but it throws out:
`Your callback function must accept the 'date_from', 'date_to' and 'sampling_interval' arguments if used with data_collection_mode 'full'.`

Thanks in advance

**Comment by 00javad00** [comment]
The issue was the wrong `arg` in the [example](https://openleadr.org/docs/reporting.html). The `sampling_rate` shall be change to `sampling_interval`.

You may change `async def load_data(date_from, date_to, sampling_rate):` to `async def load_data(date_from, date_to, sampling_interval)`:

**Comment by stan-janssen** [comment]
Thanks, I fixed the docs!
