### ISSUE TITLE
on_update_event error

### ISSUE THREAD

**Issue by muhammadvellani** [OpenLEADR/openleadr-python#74]
I am aware we are to implement on_update_event handle, but found a small bug when I was going through it the on_update_event function in client.py

https://github.com/OpenLEADR/openleadr-python/blob/2973a94d66890aeecca404e8ece6f5c3066d658c/openleadr/client.py#L672

should be 
<pre>
 if event['event_descriptor']['event_id'] in self.responded_events:
     return self.responded_events.get(event['event_descriptor']['event_id'])
</pre>
I believe self.events is in server.py not client.py

**Comment by muhammadvellani** [comment]
I found an issue with the return as well, so edited to provide fix for it. thanks

**Comment by stan-janssen** [comment]
Thanks, it's fixed in the latest version!
