### ISSUE TITLE
VEN on_updated_event handler

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#76]
Would anyone have any tips for how to incorporate a cancelled event pushed down from the VTN to VEN?

On the VTN side I am experimenting with this:

```
vtn.py

async def handle_cancel_event(request):
    """
    Handle a cancel event request.
    """
    server = request.app["server"]
    server.cancel_event(ven_id="ven_id_slipstream_ven1", event_id="our-event-id")

    tz_Chicago = pytz.timezone('America/Chicago') 
    datetime_Chicago = datetime.now(tz_Chicago)
    datetime_Chicago_formated = datetime_Chicago.strftime("%H:%M:%S")
    text = f"Event canceled now at Chicago time:, {datetime_Chicago_formated}"
    return web.Response(text=text)


# Create the server object
server = OpenADRServer(vtn_id='cloudvtn',http_host='0.0.0.0')

# Add the handler for client (VEN) registrations
server.add_handler('on_create_party_registration', on_create_party_registration)

# Add the handler for report registrations from the VEN
server.add_handler('on_register_report', on_register_report)

server.app.add_routes([
    web.get('/trigger-event', handle_trigger_event),
    web.get('/cancel-event', handle_cancel_event),
])
```

On the VEN side I am missing something on how to handle this cancelled event. Would I need to incorporate some callback here?

```
ven.py
async def on_event(event):
    # Check if we can opt in to this event
    first_signal = event['event_signals'][0]
    intervals = first_signal['intervals']
    target = event['target']
    ...
    return 'optIn'
```

On the VEN side Ill see this error:
```
An Event was updated, but you don't have an on_updated_event handler configured. You should implement your own on_update_event handler. This handler receives an Event dict and should return either 'optIn' or 'optOut' based on your choice. Will re-use the previous opt status for this event_id for now
WARNING:openleadr:An Event was updated, but you don't have an on_updated_event handler configured. You should implement your own on_update_event handler. This handler receives an Event dict and should return either 'optIn' or 'optOut' based on your choice. Will re-use the previous opt status for this event_id for now
Your on_event handler encountered an error. Will Opt Out of the event. The error was AttributeError: 'OpenADRClient' object has no attribute 'events'
ERROR:openleadr:Your on_event handler encountered an error. Will Opt Out of the event. The error was AttributeError: 'OpenADRClient' object has no attribute 'events'

Thanks for any tips!
```

**Comment by stan-janssen** [comment]
What is unclear about the message that OpenLEADR gives you?

If you create a function that accepts the event dictionary and register it like this:

```python3

def my_update_event_handler(event):
    # do something in here to cancel the event

client.add_handler('on_updated_event', my_update_event_handler)

```

You can handle your cancellations in there :-)

I see you have a `handle_cancel_event` in your **vtn** code, why is that? The VTN cancels an event, not the VEN.

**Comment by bbartling** [comment]
Thanks for the tips on the `client.add_handler` I get this now pretty easy : ) a lot like adding a handler for the VTN.

I have been day dreaming a dashboard on the VTN side, would we want to be able to push a "cancel event" from the VTN to the VEN? `handle_cancel_event` was this handler meant for the VEN? At least through a VTN dashboard I was hoping to create an event to push to the VEN but then give the flexibility to cancel the event from the VTN dashboard, maybe I am off track on my thinking? 

At least where I am the demand response is still very old school where most utility providers are still calling the building on a telephone to ask them to trim power, I don't see any automated methods of doing anything in my lifetime based on like grid signals. I think I can remember you mentioning in of your issue reply's for the [grid to maintain frequency](https://en.wikipedia.org/wiki/Droop_speed_control) we could do that wow we wouldn't need to cancel events, right? Curious on any other thoughts on this...
