### ISSUE TITLE
Add hooks for integrating functionality at various points

### ISSUE THREAD

**Issue by stan-janssen** [OpenLEADR/openleadr-python#8]
I can imagine developers wanting to hook into the code at various points during parsing, validating, formatting and sending messages. I propose we add a mechanism that will allow developers to bind functions or coroutines to certain hook points.

**Comment by finetuned89** [comment]
I want to create a nice web-base 'debugging console' that a developer can register to these hooks, to visualize the message flow and to help build the applications.

**Comment by stan-janssen** [comment]
One easy wat tot implement hooks around the request-response cycle is to use `aiohttp`s middlewares and signals.
