### ISSUE TITLE
Implementing oadrCanceledPartyRegistration response

### ISSUE THREAD

**Issue by 00javad00** [OpenLEADR/openleadr-python#81]
I understand you haven't implemented `oadrCancelPartyRegistration` on the client-side yet, but on the server-side, a service has been considered for `on_cancel_party_registration`. In my understanding, this service shall be initiated after the registration and during the polling when a `registrationID` is valid but seems on the client-side there is no mechanism to address the response to this request.
In my understanding, it should be a call under `client._poll()` to address the server request for canceling the party registration?

**Comment by abhigupta2910** [comment]
Yes, you are right. We can add the oadrCancelParty registration request under the clint._poll().

The on_cancel_party_registration can then look something like this:

``` python

async def on_cancel_party_registration(self, message):
        # Update/Delete all the registration and reports information
        self.registration_id = None
        self.report_requests = None
        self.reports = None
        self.report_callbacks = None            
        self.report_requests = None          
        self.incomplete_reports = None     
        self.pending_reports = None

        response = {'response_code': 200,
                        'response_description': 'OK',
                        'request_id': message['request_id']}
        message = self._create_message('oadrCanceledPartyRegistration',
                                        response=response)
        service = 'EiRegisterParty'
        response_type, response_payload = await self._perform_request(service, message)
        logger.info(response_type, response_payload)
```

**Comment by 00javad00** [comment]
Addition to this you need to remove all the queued job in `self.scheduler`.

**Comment by abhigupta2910** [comment]
Thanks for that @00javad00 ! Are you testing with the official test harness? We were about to purchase it to get this package 100% compliant, but if you already are testing with it, we'd be happy to work together to streamline the error testing.

**Comment by 00javad00** [comment]
@abhigupta2910 Yes, many detail shall be added to pass all the tests. Most of them are about the flow and process (i.e. the way you considered the party registration is not wrong but is not the recommended one, or using `cron` scheduler is not addressing the need and is better to use `interval` with start and end date, etc) and they are not really bugs or issues. Anyhow I will report the important ones in return to your favor of sharing this code publicly.

**Comment by abhigupta2910** [comment]
That sounds great! I'll keep tracking this repository for the issues that you post.

**Comment by stan-janssen** [comment]
This was merged previously, thanks!
