### ISSUE TITLE
Event Schedule

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#95]
VTN code question.

Can created events be accessed from a callback via an aiohttp GET endpoint?

For example if I have some code to create an event to be pushed down to a VEN like below:

```
"""
Handle a trigger event request with openleadr.
"""
server = request.app["server"]
server.add_event(ven_id=ven_id,
    signal_name='LOAD_CONTROL',
    signal_type='x-loadControlCapacity',
    intervals=[{'dtstart': event_start_utc,
                'duration': timedelta(minutes=minutes),
                'signal_payload': 1.0}],
    callback=event_response_callback,
    event_id=event_start_formatted_local_tz,
)
```

Is it possible to lookup **_all_** events configured with for server that would show event_IDs and associated VEN for the event ID? Any tips on how to implement this greatly appreciated.

**Comment by porkytin** [comment]
I think you could set up a separate database to keep track of your created events, so that every time you call the event trigger the server writes the relevant information (like ven ID and event ID) to an "events" table in the database and then call the `server.add_event()`. This way you can code another GET endpoint that queries the DB which I think is a common use case, or connect directly to the DB from another terminal.

**Comment by bbartling** [comment]
@porkytin thanks for the response, that makes perfect sense. What I envision starting out on this journey is something very small, like a just a handful of VENs all (part of the same utility demand response program) receiving the same demand response signal at one time.


Do you think [pydantic ](https://pydantic-docs.helpmanual.io/)models are a neat feature for that could be incorporated into a restful openLeadr VTN? 

I have been playing around with aiohttp-pydantic example code, morphing it into [VEN storage](https://github.com/bbartling/openadrtester/tree/main/pydantic) where thru the rest interface VENs can be updated, added, deleted, viewed, etc. See screenshot below...

Curious if anyone would be interested in collaborating at all on something like with, maybe with jwt incorporated for authentication?

The aiohttp pydantic seems sort of cool, it has swagger features built into it.

![image](https://user-images.githubusercontent.com/29737117/134914842-f4543d32-1f73-4935-9c71-c8e95cf6f825.png)

**Comment by porkytin** [comment]
I'm not familiar at all with pydantic, but if it provides a simple way to add a graphical interface for making requests to your VTN´s API I think is useful. In my case, I coded a simple client in python to make those requests (add_ven, add_event, cancel_event, etc.) and for "security purposes" I'm sending the whole private key in the request, and the server checks if it matches its own, which I don't think is a recommended way of doing these things, even if the request is encrypted. So, adding a more standard auth method with jwt to interact with the internal API would be cool.

If you go on with your project I think it could serve as an example/tutorial of how to implement OpenADR server and clients with openLEADR.

**Comment by bbartling** [comment]
@porkytin Thanks!
