### ISSUE TITLE
Not able to receive event from VTN?

### ISSUE THREAD

**Issue by chandank21** [OpenLEADR/openleadr-python#97]

**Comment by chandank21** [comment]
I am using ....    client.add_event(ven_id='ven_id_123',
                 signal_name='simple',
                 signal_type='level',
                 intervals=[{'dtstart': datetime(2021, 1, 1, 12, 0, 0, tzinfo=timezone.utc),
                             'duration': timedelta(minutes=10),
                             'signal_payload': 1}],
                 callback=event_response_callback)
at server side . and
 client.add_handler('on_event', handle_event) at client side ....i am not able to get any event.....
can u resolve this issue?

**Comment by porkytin** [comment]
Hi, I think you may be confused. Events are created on the server side, not the client. Check the specification on the openADR website.

**Comment by chandank21** [comment]
No..
I hv added event on server side using server. add_event() and fetching
event on client side event handler. But client is not fetching any event...

**Comment by chandank21** [comment]
thanks....query solved.
